### ISSUE TITLE
Error while validate license

### ISSUE THREAD

**Issue by redevrx** [bridgefy/bridgefy_flutter#40]
Bridgefy.SDK : [BridgefySDK] Did fail to start service with error: An error occurred while validating the license

**Comment by julian-bridgefy** [comment]
Hi @redevrx, we have identified that the error is related to a pending payment status on your account. To resolve this issue, we will need to validate your license and payment status.

**Comment by redevrx** [comment]
@julian-bridgefy How many devices can this SDK connect to at most?

**Comment by julian-bridgefy** [comment]
Hi @redevrx <https://github.com/redevrx>,
We received news from you in an Issue reported in github, I will help you
to solve the main issue with the SDK license validation, in the Bridgefy
developer site is shown the invoice list for your visualization,
https://developer.bridgefy.me/billing/cards let me know if you can see it,
when there is a pending invoice the SDK can not be initialized, it is
necessary to have the account settled to continue.

Concerning your second question; the Bridgefy SDK ideally establishes up to
7 connections per node, but the number of connections that can be
established can vary depending on factors such as device hardware, network
conditions and the specific implementation of the SDK in your application.


*Gilberto Julián de la Orta*
CTO
Bridgefy – Making Apps Work Without Internet
www.bridgefy.me

What is Bridgefy? Click here to watch the video!
<http://www.bit.ly/bridgefysdk>

The contents of this message do not represent in any legal or official way
the opinions, decisions or postures of any company whatsoever. Nothing in
this message is intended to constitute an electronic signature unless a
specific statement to the contrary is included in this message.
Reproduction of parts or the entirety of this message is prohibited if not
expressly permitted by the sender.

**Comment by julian-bridgefy** [comment]
In the Bridgefy developer site is shown the invoice list for your visualization, https://developer.bridgefy.me/billing/cards let me know if you can see it, when there is a pending invoice the SDK can not be initialized, it is necessary to have the account settled to continue.

Concerning your second question; the Bridgefy SDK ideally establishes up to 7 connections per node, but the number of connections that can be established can vary depending on factors such as device hardware, network conditions and the specific implementation of the SDK in your application.

**Comment by redevrx** [comment]
> @redevrx In the Bridgefy developer site is shown the invoice list for your visualization, https://developer.bridgefy.me/billing/cards let me know if you can see it, when there is a pending invoice the SDK can not be initialized, it is necessary to have the account settled to continue.
> 
> Concerning your second question; the Bridgefy SDK ideally establishes up to 7 connections per node, but the number of connections that can be established can vary depending on factors such as device hardware, network conditions and the specific implementation of the SDK in your application.

@julian-bridgefy billing have status success
![messageImage_1727144563566](https://github.com/user-attachments/assets/ea0f6e96-0b9d-411f-a57e-fa92f15a3fb4)

**Comment by julian-bridgefy** [comment]
@redevrx  let's investigate the problem, in order not to compromise the sensitive information I just need to confirm the name of the license created in the Dashboard, is `TG-Cabin-Connect`?

**Comment by redevrx** [comment]
Yes

**Comment by redevrx** [comment]
@julian-bridgefy  have error license on iOS but android working

[TG Hero Log] 
              'package:bridgefy/bridgefy_method_channel.dart': Failed assertion: line 110 pos 12: 'started': Bridgefy is not started
              #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
              #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
              #2      MethodChannelBridgefy.currentUserID (package:bridgefy/bridgefy_method_channel.dart:110:12)
              <asynchronous suspension>
              #3      BridgefyUtils.initClient.<anonymous closure> (package:tg_crewkit/services/bridgefy_utils.dart:123:25)
              <asynchronous suspension>
              #4      BridgefyUtils.initClient (package:tg_crewkit/services/bridgefy_utils.dart:122:7)
              <asynchronous suspension>
[TG Hero Log] 
              BridgefyError (type: licenseError, code: 0, message: An error occurred while validating the license)

**Comment by julian-bridgefy** [comment]
@redevrx  the error may be caused by the SDK uninitialization, I suggest you follow these steps:
You must create a single instance
```dart
import 'package:bridgefy/bridgefy.dart';
final _bridgefy = Bridgefy();
```

1. Initializes the Bridgefy SDK with the given API key and verbose logging.
```dart
_bridgefy.initialize(
  apiKey: "<API_KEY>",
  delegate: this,
  verboseLogging: true,
);
```
2. After initializing the SDK, you should call the `start()` function to have the SDK's services running.
```dart
_bridgefy.start(
  userId: "Custom UUID",
  propagationProfile: BridgefyPropagationProfile.standard,
);
```

You must initialize the SDK first and then start.

Remember that the bundle ID of the iOS app and Android application ID must be the same as the one registered in the license in Bridgefy Dashboard.

**Comment by redevrx** [comment]
@julian-bridgefy I try with you recommend 

[TG Hero Log] 
              'package:bridgefy/bridgefy_method_channel.dart': Failed assertion: line 110 pos 12: 'started': Bridgefy is not started
              #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
              #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
              #2      MethodChannelBridgefy.currentUserID (package:bridgefy/bridgefy_method_channel.dart:110:12)
              <asynchronous suspension>
              #3      BridgefyUtils.initClient.<anonymous closure> (package:tg_crewkit/services/bridgefy_utils.dart:134:25)
              <asynchronous suspension>
              #4      BridgefyUtils.initClient (package:tg_crewkit/services/bridgefy_utils.dart:133:7)
              <asynchronous suspension>
[TG Hero Log] 
              BridgefyError (type: licenseError, code: 0, message: An error occurred while validating the license)

**Comment by redevrx** [comment]
@julian-bridgefy 

```dart
 await _bridgefy.start(
        userId: _clientUUid,
        propagationProfile: BridgefyPropagationProfile.standard,
      );
      ///not have error but not start service
      
      
      await _bridgefy.currentUserID;
      ////error not start service
```

**Comment by julian-bridgefy** [comment]
We test with your API KEY and bundleID/androidId and the SDK initializes and start correctly, please double check bundle ID and application ID in your project was registered in the license.

**Comment by redevrx** [comment]
@julian-bridgefy 

> We test with your API KEY and bundleID/androidId and the SDK initializes and start correctly, please double check bundle ID and application ID in your project was registered in the license.

@julian-bridgefy I check bundle Id and start
![IntelliJ Snippet](https://github.com/user-attachments/assets/de3f5d89-73ad-437e-9334-2edaee4c5953)

**Comment by julian-bridgefy** [comment]
Hi @redevrx  thanks for the image, I see you are calling the `connectedPeers` before the SDK is initialized and started, I recommend you use the SDK methods after initializing and starting it.

**Comment by redevrx** [comment]
@julian-bridgefy you can help check api key ?
bundle Id matches in desborad
![IntelliJ Snippet (3)](https://github.com/user-attachments/assets/c3248fc4-072d-431f-8663-06ac151a6af8)

**Comment by julian-bridgefy** [comment]
@redevrx  we have tested with the bundle ID with your api key and we were able to initialize and start the iOS SDK, however we are going to test iOS with the Flutter sample app, we will have news today about this issue ASAP

**Comment by redevrx** [comment]
I try using flutter examples error validated license

**Comment by julian-bridgefy** [comment]
Thanks for the tip, that simplifies things, inside the example folder there are instructions on how to configure the project, here you have the file, and you probably have to update or create a license with the bundle ID and application ID corresponding to the example.

The license you created, contains different bundleID/applicationID to the example project, we tested with this license and everything is ok.

https://github.com/bridgefy/bridgefy_flutter/blob/main/example/README.md
